apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-pvc
  namespace: devops-pipeline
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: devops-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:latest
          args: ["-config.file=/etc/loki/local-config.yaml"]
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: config
              mountPath: /etc/loki/local-config.yaml
              subPath: loki.yaml
            - name: data
              mountPath: /loki
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
      volumes:
        - name: config
          configMap:
            name: loki-config
        - name: data
          persistentVolumeClaim:
            claimName: loki-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: devops-pipeline
spec:
  selector:
    app: loki
  ports:
    - port: 3100
      targetPort: 3100
