all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/devops-pipeline.pem
    ansible_python_interpreter: /usr/bin/python3

  children:
    # Servers managed directly (non-K8s)
    bastion:
      hosts:
        bastion-01:
          ansible_host: "{{ lookup('env', 'BASTION_IP') }}"

    app_servers:
      hosts:
        app-01:
          ansible_host: "{{ lookup('env', 'APP_SERVER_IP') }}"
