import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  LayoutDashboard,
  Loader2,
  LogIn,
  LucideProps,
  ShoppingBag,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  Sun,
  Trash,
  Twitter,
  User,
  UserCircle,
  UserPen,
  UserX,
  X,
  Kanban,
  Github,
  Folder,
  Users,
  Crown,
  Star,
  Box,
  Palette
} from 'lucide-react';

export type Icon = React.ComponentType<LucideProps>;

export const Icons = {
  dashboard: LayoutDashboard,
  logo: Command,
  login: LogIn,
  close: X,
  product: Box,
  palette: Palette,
  spinner: Loader2,
  kanban: Kanban,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  employee: UserX,
  post: FileText,
  page: File,
  userPen: UserPen,
  user2: UserCircle,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: Sun,
  moon: Moon,
  laptop: Laptop,
  github: Github,
  twitter: Twitter,
  check: Check,
  workspace: Folder,
  teams: Users,
  pro: Crown,
  exclusive: Star,
  account: UserCircle,
  profile: User
};
