dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu-2204
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    privileged: true
    init: true
    command: sleep infinity
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: /workspaces/devops-pipeline/ansible/roles
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible/tmp
      gather_timeout: 15
  inventory:
    host_vars:
      ubuntu-2204:
        ansible_user: root
        ansible_connection: community.docker.docker_api
verifier:
  name: ansible
